name: "CI - JDK 17 Build"

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/project.yml'
  pull_request:
    branches: [ main ]


jobs:
  build-jdk17:
    name: "JDK 17 Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Build
        run: mvn clean install

